kind: Service
apiVersion: v1
metadata:
  name: pihole-web-service
  namespace : pihole-system
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name : web
  type: LoadBalancer